FORMAT: 1A
HOST: http://teamdirectory.apiblueprint.org/

# TeamDirectory

## Users Collection [/api/users]

### Get User by id [GET /api/users/{id}]
+ Parameters
    + id(number, required) - Id of a User
    
+ Response 200 (application/json)

        
            {
                "id": 123,
                "name": "John Doe",
                "age": 20,
                "astrologicalSign": "Virgo",
                "course": "Wirtschaftsinformatik"
            }
    

## Comments Collection [/api/comments/]

### Create a New Comment [POST]
+ Request (application/json)

        {
            "posterId": 123,
            "receiverId": 321,
            "body": "Lorem ipsum dolor sit amet"
        }

+ Response 201 (application/json)

    + Body
    
            {   
                "id": 1,
                "posterId": 123,
                "receiverId": 321,
                "author": "John Doe",
                "date": "15.06.2018",
                "time": "03:54",
                "content": "Lorem ipsum dolor sit amet"
            }


### Get a comment by receiverId [GET /api/comments?receiverId={receiverId}]
    + Request
        + receiverId(number, requeired) - Id of the receiver

+ Response 200 (application/json)
        
            
            {   
                "id": 1,
                "posterId": 123,
                "receiverId": 321,
                "author": "John Doe",
                "date": "15.06.2018",
                "time": "03:54",
                "content": "Lorem ipsum dolor sit amet"
            }

### Get a comment by posterId [GET /api/comments?receiverId={posterId}]
    + Request
        + receiverId(number, requeired) - Id of the receiver

+ Response 200 (application/json)
        
            
            {   
                "id": 1,
                "posterId": 123,
                "receiverId": 321,
                "author": "John Doe",
                "date": "15.06.2018",
                "time": "03:54",
                "content": "Lorem ipsum dolor sit amet"
            }